[package]
name = "kokplatta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.0", features = ["derive"] }
serde = "1.0.188"
serde_derive = "1.0.188"
toml = "0.7.6"
